training_data = [
    # Total Orders Examples
    ("How many orders did we place last month?", "total_orders"),
    ("How many orders were created last month?", "total_orders"),
    ("What’s the count of orders placed in the previous month?", "total_orders"),
    ("How many orders were placed last month?", "total_orders"),
    ("Show total orders for last month.", "total_orders"),
    ("Total number of orders in Q1", "total_orders"),
    ("How many orders are there this fiscal year?", "total_orders"),
    ("Total orders created during July.", "total_orders"),
    ("What was the total number of orders placed?", "total_orders"),
    ("Count of all orders placed last quarter?", "total_orders"),
    ("How many orders did we have in the second half?", "total_orders"),
    ("How many orders were placed in the last fiscal year?", "total_orders"),
    ("What’s the total order count for this month?", "total_orders"),
    ("Can you give the number of orders this year?", "total_orders"),
    ("Show me the total orders in the past 30 days.", "total_orders"),
    ("List the total orders made during Q4.", "total_orders"),
    ("What was the total number of orders placed recently?", "total_orders"),
    ("How many orders did we have this year?", "total_orders"),
    ("Show total order count for previous months.", "total_orders"),
    
    # Highest Spending Quarter Examples
    ("Which quarter had the highest spending?", "highest_spending_quarter"),
    ("Show me the quarter with maximum expenditure.", "highest_spending_quarter"),
    ("What was the spending in Q3?", "highest_spending_quarter"),
    ("Which quarter had the most expenses?", "highest_spending_quarter"),
    ("Identify the quarter with the highest spending.", "highest_spending_quarter"),
    ("Show spending trends over the last quarter.", "highest_spending_quarter"),
    ("Which quarter saw the highest procurement?", "highest_spending_quarter"),
    ("What quarter had the peak spending?", "highest_spending_quarter"),
    ("In which quarter was the expenditure the highest?", "highest_spending_quarter"),
    ("Can you tell me which quarter had the most spending?", "highest_spending_quarter"),
    ("During which quarter was the most money spent?", "highest_spending_quarter"),
    ("What quarter had the highest purchasing volume?", "highest_spending_quarter"),
    ("Which quarter had the largest expenditures?", "highest_spending_quarter"),
    ("What quarter has the top spending amount?", "highest_spending_quarter"),
    ("Tell me the quarter with the highest procurement costs.", "highest_spending_quarter"),

    # Frequently Ordered Items Examples
    ("What are the most frequently ordered items?", "frequently_ordered_items"),
    ("List top purchased items.", "frequently_ordered_items"),
    ("Show top 5 ordered items.", "frequently_ordered_items"),
    ("List all frequently ordered commodities.", "frequently_ordered_items"),
    ("Which items are ordered most often?", "frequently_ordered_items"),
    ("What items have been purchased most frequently?", "frequently_ordered_items"),
    ("Frequently bought items?", "frequently_ordered_items"),
    ("Top recurring purchases?", "frequently_ordered_items"),
    ("What products are ordered on a regular basis?", "frequently_ordered_items"),
    ("Show the top items purchased over the last year.", "frequently_ordered_items"),
    ("List commonly ordered goods.", "frequently_ordered_items"),
    ("What products are requested most frequently?", "frequently_ordered_items"),
    ("What are the most repeated purchases?", "frequently_ordered_items"),
    ("Items purchased multiple times?", "frequently_ordered_items"),
    ("Show me the list of top-ordered items.", "frequently_ordered_items"),
    
    # Highest Single Order Examples
    ("What is the highest amount spent in a single order?", "highest_single_order"),
    ("Tell me the largest purchase made.", "highest_single_order"),
    ("What’s the most expensive single order?", "highest_single_order"),
    ("What was the biggest order in terms of cost?", "highest_single_order"),
    ("Find the top single order amount.", "highest_single_order"),
    ("What’s the costliest order placed?", "highest_single_order"),
    ("Tell me the highest-priced order.", "highest_single_order"),
    ("Which order has the largest amount spent?", "highest_single_order"),
    ("Show me the single most expensive purchase.", "highest_single_order"),
    ("What’s the highest single order total?", "highest_single_order"),
    
    # Top Supplier Examples
    ("Which supplier received the highest number of orders?", "top_supplier"),
    ("Who is the top supplier by order count?", "top_supplier"),
    ("Which supplier has the most orders?", "top_supplier"),
    ("Tell me the supplier with the largest number of orders.", "top_supplier"),
    ("Show me the top suppliers by volume.", "top_supplier"),
    ("List the suppliers with most orders.", "top_supplier"),
    ("Top suppliers by number of purchases?", "top_supplier"),
    ("Who are the most frequently used suppliers?", "top_supplier"),
    ("Which supplier do we order from most often?", "top_supplier"),
    ("Give the name of the supplier with the highest order count.", "top_supplier"),
    
    # Top Department Examples
    ("Find the department with the highest spending.", "top_department"),
    ("Which department placed the most orders?", "top_department"),
    ("Show me the department with the largest expenditure.", "top_department"),
    ("List the departments by spending amount.", "top_department"),
    ("Which department spent the most?", "top_department"),
    ("Who are the top spenders by department?", "top_department"),
    ("What department has the highest number of orders?", "top_department"),
    ("Department with the largest order volume?", "top_department"),
    ("Which department has the top purchasing total?", "top_department"),
    ("List the departments with the most spending.", "top_department"),
    
    # Total Spending Examples
    ("What was the total spending last year?", "total_spending"),
    ("Show total expenditure this fiscal year.", "total_spending"),
    ("How much was spent overall?", "total_spending"),
    ("What’s the total amount spent this year?", "total_spending"),
    ("Tell me the total spending amount.", "total_spending"),
    ("How much have we spent so far?", "total_spending"),
    ("Give me the overall expenditure.", "total_spending"),
    ("What’s our total procurement cost?", "total_spending"),
    ("Total spending for all departments?", "total_spending"),
    ("Show the total amount of purchases made.", "total_spending"),

    # Spending on Specific Items
    ("How much was spent on office supplies?", "spending_on_supplies"),
    ("Show the spending on IT services.", "spending_on_services"),
    ("What was the cost of purchasing furniture?", "spending_on_furniture"),
    ("List total spending for IT goods.", "spending_on_IT_goods"),
    ("What’s the spending on healthcare items?", "spending_on_healthcare"),
    ("Show me the total cost for non-IT services.", "spending_on_nonIT_services"),
    ("How much was spent on transportation?", "spending_on_transportation"),
    ("What is the spending on cleaning supplies?", "spending_on_cleaning_supplies"),
    ("Total amount spent on electronic goods?", "spending_on_electronics"),
    ("Give me the spending for educational materials.", "spending_on_education_materials"),
]
